export const P2P_USER_OFFER_FETCH = 'p2pUserOffer/P2P_USER_OFFER_FETCH';
export const P2P_USER_OFFER_DATA = 'p2pUserOffer/P2P_USER_OFFER_DATA';
export const P2P_USER_OFFER_ERROR = 'p2pUserOffer/P2P_USER_OFFER_ERROR';

export const P2P_USER_OFFER_CREATE = 'p2pUserOffer/P2P_USER_OFFER_CREATE';
export const P2P_USER_OFFER_CREATE_DATA = 'p2pUserOffer/P2P_USER_OFFER_CREATE_DATA';
export const P2P_USER_OFFER_CREATE_ERROR = 'p2pUserOffer/P2P_USER_OFFER_CREATE_ERROR';

export const P2P_USER_OFFER_CANCEL = 'p2pUserOffer/P2P_USER_OFFER_CANCEL';
export const P2P_USER_OFFER_CANCEL_DATA = 'p2pUserOffer/P2P_USER_OFFER_CANCEL_DATA';
export const P2P_USER_OFFER_CANCEL_ERROR = 'p2pUserOffer/P2P_USER_OFFER_CANCEL_ERROR';
