export const P2P_PROFILE_FETCH = 'p2pProfile/FETCH';
export const P2P_PROFILE_FETCH_DATA = 'p2pProfile/DATA';
export const P2P_PROFILE_FETCH_ERROR = 'p2pProfile/ERROR';

export const P2P_PROFILE_CHANGE_USERNAME = 'p2pProfile/CHANGE_USERNAME';
export const P2P_PROFILE_CHANGE_USERNAME_DATA = 'p2pProfile/CHANGE_USERNAME_DATA';
export const P2P_PROFILE_CHANGE_USERNAME_ERROR = 'p2pProfile/CHANGE_USERNAME_ERROR';

export const P2P_PROFILE_BLOCK_MERCHANT = 'p2pProfile/BLOCK_MERCHANT';
export const P2P_PROFILE_BLOCK_MERCHANT_DATA = 'p2pProfile/BLOCK_MERCHANT_DATA';
export const P2P_PROFILE_BLOCK_MERCHANT_ERROR = 'p2pProfile/BLOCK_MERCHANT_ERROR';

export const P2P_PROFILE_LIST_BLOCK_MERCHANT = 'p2pProfile/LIST_BLOCK_MERCHANT';
export const P2P_PROFILE_LIST_BLOCK_MERCHANT_DATA = 'p2pProfile/LIST_BLOCK_MERCHANT_DATA';
export const P2P_PROFILE_LIST_BLOCK_MERCHANT_ERROR = 'p2pProfile/LIST_BLOCK_MERCHANT_ERROR';
