export const P2P_USER_OFFER_DETAIL_FETCH = 'p2pUserOffer/P2P_USER_OFFER_DETAIL_FETCH';
export const P2P_USER_OFFER_DETAIL_DATA = 'p2pUserOffer/P2P_USER_OFFER_DETAIL_DATA';
export const P2P_USER_OFFER_DETAIL_ERROR = 'p2pUserOffer/P2P_USER_OFFER_DETAIL_ERROR';

export const P2P_USER_OFFER_DETAIL_CREATE = 'p2pUserOffer/P2P_USER_OFFER_DETAIL_CREATE';
export const P2P_USER_OFFER_DETAIL_CREATE_DATA = 'p2pUserOffer/P2P_USER_OFFER_DETAIL_CREATE_DATA';
export const P2P_USER_OFFER_DETAIL_CREATE_ERROR = 'p2pUserOffer/P2P_USER_OFFER_DETAIL_CREATE_ERROR';
